dbt_demo:
  outputs:
    dev:
      type: spark
      method: thrift
      host: localhost
      port: 10000
      schema: raw
      database: raw
      user: dbt
      connect_retries: 5
      connect_timeout: 10
      retry_all: True
      use_ssl: False
  target: dev